=== droneshire/ti/ccsv7/ccs_base/DebugServer/schemas/breakpoints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="breakpoints">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="group" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="breakpoint" type="breakpoint_type" minOccurs="0" maxOccurs="unbounded"/>					
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:complexType name="breakpoint_type">
		<xs:sequence>
			<xs:element name="property" type="property_type" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="enabled" type="xs:boolean"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="property_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:choice minOccurs="0">
				<xs:element name="boolean" type="xs:boolean"/>
				<xs:element name="file" type="xs:string"/>
				<xs:element name="integer" type="xs:integer"/>
				<xs:element name="location" type="location_type"/>
				<xs:element name="string" type="xs:string"/>
			</xs:choice>
			<xs:element name="property" type="property_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="location_type">
		<xs:sequence>
			<xs:choice>
				<xs:element name="address" type="xs:integer"/>
				<xs:element name="expression" type="xs:string"/>
				<xs:element name="source">
					<xs:complexType>
						<xs:all>
							<xs:element name="symbol_file" type="xs:string"/>
							<xs:element name="filename" type="xs:string"/>
							<xs:element name="line" type="xs:integer"/>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name="page" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== droneshire/ti/ccsv7/ccs_base/common/analysis/usecases/emu/triggers/STM/J6ECO_SC_Memory_Throughput_Analysis_Job1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<breakpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="breakpoints.xsd">

  <breakpoint type="AET">
    <property>
      <name>Hardware Configuration</name>
      <property>
        <name>Type</name>
        <string>Trace</string>
        <property>
            <name>STM Trace Type</name>
            <string>Performance Probe</string>
            <property>
              <name>Use Cases</name>
              <string>Average Burst Length</string>
              <property>
                <name>Subsystem Type</name>
                <string>EMIF1_SYS</string>
              </property>
              <property>
                <name>Transaction Type</name>
                <string>Read and Write</string>
              </property>
              <property>
                <name>Transaction Filter</name>
                <string></string>
                <property>
                  <name>Initiator Enable</name>
                  <string>All Initiators</string>
                </property>
                <property>
                  <name>ReqInfo Setting</name>
                  <string></string>
                  <property>
                    <name>Priority[2]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Priority[1]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Priority[0]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>DMA_Channel_ID[4]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>DMA_Channel_ID[3]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>DMA_Channel_ID[2]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>DMA_Channel_ID[1]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>DMA_Channel_ID[0]</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Valid CPU ID</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Invalid CPU ID</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Endianness</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Domain 2</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Domain 1</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Domain 0</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Secure Mode</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Debug Mode</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Supervisor</name>
                    <string>Don't Care</string>
                  </property>
                  <property>
                    <name>Type[0]</name>
                    <string>Don't Care</string>
                  </property>
                </property>
              </property>
              <property>
                <name>Sample Window Size</name>
                <integer>4095</integer>
              </property>
            </property>
            <property>
              <name>Trigger Type</name>
              <string>Permanent</string>
            </property>
            <property>
              <name>Export Type</name>
              <string>Auto</string>
            </property>
            <property>
              <name>Dump Mode</name>
              <string>Unconditional</string>
            </property>
            </property>
      </property>
    </property>
    <property>
      <name>Miscellaneous</name>
      <property>
        <name>Group</name>
        <string>Default Group</string>
      </property>
      <property>
        <name>Name</name>
        <string>Throughput RW EMIF0</string>
      </property>
    </property>
    <enabled>0</enabled>
  </breakpoint>

</breakpoints>
