=== droneshire/ti/ccsv7/ccs_base/DebugServer/schemas/breakpoints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="breakpoints">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="group" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="breakpoint" type="breakpoint_type" minOccurs="0" maxOccurs="unbounded"/>					
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:complexType name="breakpoint_type">
		<xs:sequence>
			<xs:element name="property" type="property_type" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="enabled" type="xs:boolean"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="property_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:choice minOccurs="0">
				<xs:element name="boolean" type="xs:boolean"/>
				<xs:element name="file" type="xs:string"/>
				<xs:element name="integer" type="xs:integer"/>
				<xs:element name="location" type="location_type"/>
				<xs:element name="string" type="xs:string"/>
			</xs:choice>
			<xs:element name="property" type="property_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="location_type">
		<xs:sequence>
			<xs:choice>
				<xs:element name="address" type="xs:integer"/>
				<xs:element name="expression" type="xs:string"/>
				<xs:element name="source">
					<xs:complexType>
						<xs:all>
							<xs:element name="symbol_file" type="xs:string"/>
							<xs:element name="filename" type="xs:string"/>
							<xs:element name="line" type="xs:integer"/>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name="page" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== droneshire/ti/ccsv7/ccs_base/common/analysis/usecases/emu/triggers/STM/AM43x_SC_Memory_Throughput_Analysis_Job1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<breakpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="breakpoints.xsd">

  <breakpoint type="AET">
    <property>
      <name>Hardware Configuration</name>
      <property>
        <name>Type</name>
        <string>Trace</string>
        <property>
          <name>STM Trace Type</name>
          <string>Performance Probe</string>
          <property>
            <name>Use Cases</name>
            <string>ThroughPut per Sampling Period</string>
            <property>
              <name>Subsystem Type</name>
              <string>EMIF</string>
            </property>
            <property>
              <name>Transaction Type</name>
              <string>Read</string>
            </property>
            <property>
              <name>Transaction Filter</name>
              <string></string>
              <property>
                <name>Initiator Enable</name>
                <string>All Initiators</string>
              </property>
              <property>
                <name>ReqInfo Setting</name>
                <string></string>
                <property>
                  <name>DMA Channel ID[3]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>DMA Channel ID[2]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>DMA Channel ID[1]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>DMA_Channel_ID[0]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Priority[2]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Priority[1]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Priority[0]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Invalid CPU Id</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Valid CPU ID</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Domain[2]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Domain[1]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Domain[0]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Secure Mode</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Supervisor</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Type[1]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Type[0]</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Endianess</name>
                  <string>Don't Care</string>
                </property>
                <property>
                  <name>Debug</name>
                  <string>Don't Care</string>
                </property>
              </property>
            </property>
            <property>
              <name>Sample Window Size</name>
              <integer>4095</integer>
            </property>
            <property>
              <name>Enable Address Range Limit</name>
              <boolean>0</boolean>
            </property>
          </property>
          <property>
            <name>Trigger Type</name>
            <string>Permanent</string>
          </property>
          <property>
            <name>Export Type</name>
            <string>Auto</string>
          </property>
          <property>
            <name>Dump Mode</name>
            <string>Unconditional</string>
          </property>
        </property>
      </property>
    </property>
    <property>
      <name>Miscellaneous</name>
      <property>
        <name>Group</name>
        <string>Default Group</string>
      </property>
      <property>
        <name>Name</name>
        <string>STM Trace</string>
      </property>
    </property>
    <enabled>1</enabled>
  </breakpoint>

</breakpoints>

=== droneshire/ti/ccsv7/ccs_base/common/analysis/usecases/emu/triggers/DSP/Statistical_Profiling_Job1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<breakpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="breakpoints.xsd">

  <breakpoint type="AET">
    <property>
      <name>Hardware Configuration</name>
      <property>
        <name>Type</name>
        <string>Trace</string>
        <property>
          <name>Trace Type</name>
          <string>Standard</string>
        </property>
        <property>
          <name>Actions</name>
          <string>User Script</string>
          <property>
            <name>Script Type</name>
            <string>Statistical Profile</string>
            <property>
              <name>Cycle Count</name>
              <integer>1000</integer>
            </property>
          </property>
        </property>
      </property>
    </property>
    <property>
      <name>Miscellaneous</name>
      <property>
        <name>Group</name>
        <string>Default Group</string>
      </property>
      <property>
        <name>Name</name>
        <string>Statistical Function Profiling</string>
      </property>
    </property>
    <enabled>0</enabled>
  </breakpoint>

</breakpoints>

=== droneshire/ti/ccsv7/ccs_base/common/analysis/usecases/emu/triggers/DSP/Cache_Event_Analysis_Job5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<breakpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="breakpoints.xsd">

	<breakpoint type="AET">
		<property>
			<name>Hardware Configuration</name>
			<property>
				<name>Type</name>
				<string>Trace</string>
				<property>
					<name>Trace Type</name>
					<string>Event</string>
				</property>
				<property>
				  <name>Actions</name>
				  <string>End All Trace</string>
				</property>
				<property>
				  <name>Trigger Type</name>
				  <string>PC</string>
				  <property>
					<name>Location Type</name>
					<string>Point</string>
					<property>
					  <name>Location</name>
					  <location>
						<address>0</address>
						<page>0</page>
					  </location>
					</property>
				  </property>
				  <property>
					<name>Trigger Skip/Delay</name>
					<string>No</string>
				  </property>
				</property>
				<property>
					<name>Global Category</name>
					<string>Memory</string>
					<property>
						<name>Event 1</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>1</boolean>
							<property>
								<name>Hits L2 SRAM</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits L2 Cache</name>
								<boolean>0</boolean>
							</property>
							<property>
								<name>Hits External</name>
								<boolean>0</boolean>
							</property>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Event 2</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>1</boolean>
							<property>
								<name>Hits L2 SRAM</name>
								<boolean>0</boolean>
							</property>
							<property>
								<name>Hits L2 Cache</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits External</name>
								<boolean>0</boolean>
							</property>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Event 3</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>1</boolean>
							<property>
								<name>Hits L2 SRAM</name>
								<boolean>0</boolean>
							</property>
							<property>
								<name>Hits L2 Cache</name>
								<boolean>0</boolean>
							</property>
							<property>
								<name>Hits External</name>
								<boolean>1</boolean>
							</property>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Event 4</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Advanced</name>
						<string></string>
						<property>
							<name>Encoding Mode</name>
							<string>Generic</string>
						</property>
					</property>
				</property>
			</property>
		</property>
		<property>
			<name>Miscellaneous</name>
			<property>
				<name>Group</name>
				<string>Default Group</string>
			</property>
			<property>
				<name>Name</name>
				<string>Cache Analysis - End All</string>
			</property>
		</property>
		<enabled>0</enabled>
	</breakpoint>

</breakpoints>

=== droneshire/ti/ccsv7/ccs_base/common/analysis/usecases/emu/triggers/DSP/Cache_Event_Analysis_L1D.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<breakpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="breakpoints.xsd">

	<breakpoint type="AET">
		<property>
			<name>Hardware Configuration</name>
			<property>
				<name>Type</name>
				<string>Trace</string>
				<property>
					<name>Trace Type</name>
					<string>Event</string>
				</property>
				<property>
					<name>Actions</name>
					<string>Trace On</string>
				</property>
				<property>
					<name>Global Category</name>
					<string>Memory</string>
					<property>
						<name>Event 1</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>1</boolean>
							<property>
								<name>Hits L2 SRAM</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits L2 Cache</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits External Cacheable</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits External non-Cacheable</name>
								<boolean>1</boolean>
							</property>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Event 2</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>1</boolean>
							<property>
								<name>Hits L2 SRAM</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits L2 Cache</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits External Cacheable</name>
								<boolean>1</boolean>
							</property>
							<property>
								<name>Hits External non-Cacheable</name>
								<boolean>1</boolean>
							</property>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Event 3</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>1</boolean>
							<property>
								<name>Write Buf Not Full</name>
								<boolean>0</boolean>
							</property>
							<property>
								<name>Write Buf Full</name>
								<boolean>1</boolean>
							</property>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Event 4</name>
						<string></string>
						<property>
							<name>L1P Read Hit</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1P Read Miss</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Hit Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Read Miss Path B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>L1D Write Miss Path B</name>
							<boolean>1</boolean>
							<property>
								<name>Write Buf Not Full</name>
								<boolean>0</boolean>
							</property>
							<property>
								<name>Write Buf Full</name>
								<boolean>1</boolean>
							</property>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush A</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>Tag/Victim/Write Buf Flush B</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-CPU Bank Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-Snoop Conflict</name>
							<boolean>0</boolean>
						</property>
						<property>
							<name>CPU-IDMA/EDMA Bank Conflict</name>
							<boolean>0</boolean>
						</property>
					</property>
					<property>
						<name>Advanced</name>
						<string></string>
						<property>
							<name>Encoding Mode</name>
							<string>Generic</string>
						</property>
					</property>
				</property>
			</property>
		</property>
		<property>
			<name>Miscellaneous</name>
			<property>
				<name>Group</name>
				<string>Default Group</string>
			</property>
			<property>
				<name>Name</name>
				<string>L1D Cache Miss Analysis</string>
			</property>
		</property>
		<enabled>0</enabled>
	</breakpoint>

</breakpoints>

=== droneshire/ti/ccsv7/ccs_base/common/analysis/usecases/emu/triggers/STM/Vayu_System_Analysis_Job3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<breakpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="breakpoints.xsd">

  <breakpoint type="AET">
    <property>
      <name>Hardware Configuration</name>
      <property>
        <name>Type</name>
        <string>Trace</string>
        <property>
          <name>STM Trace Type</name>
          <string>System Event Detection(EVE3)</string>
          <property>
            <name>Signal Type</name>
            <string>Low Level</string>
          </property>
          <property>
            <name>Msg Generation Type</name>
            <string>in Sampling Window</string>
            <property>
              <name>Sampling Window(cycles)</name>
              <integer>255</integer>
            </property>
          </property>
          <property>
            <name>Start on Ext. Trigger</name>
            <boolean>0</boolean>
          </property>
          <property>
            <name>Stop on Ext. Trigger</name>
            <boolean>0</boolean>
          </property>
          <property>
            <name>Event Selection</name>
            <string></string>
            <property>
              <name>tpcc_aet_start</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>tpcc_aet_stop</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>ARP32 Int4</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>ARP32 Int5</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>ARP32 Int6</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>ARP32 Int7</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>VCOP Loop Start</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>VCOP Done</name>
              <boolean>1</boolean>
            </property>
            <property>
              <name>ARP32 NMI</name>
              <boolean>1</boolean>
            </property>
          </property>
        </property>
      </property>
    </property>
    <property>
      <name>Miscellaneous</name>
      <property>
        <name>Group</name>
        <string>Default Group</string>
      </property>
      <property>
        <name>Name</name>
        <string>SMSET EVE3</string>
      </property>
    </property>
    <enabled>1</enabled>
  </breakpoint>

</breakpoints>
